#!/usr/bin/env python3

import os
import subprocess
import sys
import getpass

def create(project_name):
    # Create a new folder for the project
    project_path = '/Users/felix/Documents/Master folder/CareerDev/Github Projects/AI and ML/' + project_name
    os.makedirs(project_path)

    # Prompt the user to select the Python version for the virtual environment
    python_version = input('Enter the Python version (e.g. 3.8): ')

    # Create a new Conda virtual environment with the same name as the project
    subprocess.run(['conda', 'create', '-n' + project_name, f'python={python_version}'])

    # Initialize a Git repository in the project folder
    subprocess.run(['git', 'init', project_path])

    # Create a new repository on GitHub
    username = input('Enter your GitHub username: ')
    password = getpass.getpass('Enter your GitHub password: ')
    subprocess.run(['curl', '-u', f'{username}:{password}',
                    'https://api.github.com/user/repos',
                    '-d', f'{{ "name": "{project_name}" }}'])

    # Connect the local repository to the new GitHub repository
    remote_url = f'https://github.com/{username}/{project_name}.git'
    subprocess.run(['git', 'remote', 'add', 'origin', remote_url], cwd=project_path)

    # Push the commit to the remote origin
    subprocess.run(['git', 'push', '-u', 'origin', 'main'], cwd=project_path)

    # Open the project folder in Visual Studio Code
    subprocess.run(['code', '.'], cwd=project_path)

if __name__ == '__main__':
    # Get the project name from the command line argument
    project_name = sys.argv[1]
    create(project_name)
